server {
    listen 80;
    server_name _;
    root /www/public;
    index index.php;
    charset utf-8;
    server_tokens off;
    client_max_body_size 1m;
    resolver 127.0.0.11 valid=10s ipv6=off;

    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-Content-Type-Options nosniff always;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /index.php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /www/public/index.php;
        fastcgi_param HTTP_PROXY "";
        set $php_upstream php:9000;
        fastcgi_pass $php_upstream;
        fastcgi_read_timeout 60s;
    }

    location ~ \.php$ { return 404; }
    location ~ /\. { deny all; }
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt { access_log off; log_not_found off; }
}
